package code;

import java.util.Random;
import java.util.Scanner;

public class advNumGuess {

	public static void Main(String[] args) {
		// TODO Auto-generated method stub

		Scanner input = new Scanner(System.in);
		Random rng = new Random();
		
		//Initializations of variables 
		int userNum = 0;
		int tries = 3;
		boolean playAgain = false;
		int win = 0;
		int lose = 0;
		int min = 1;
		int max = 0;
		int totalPlayed = 0;
		int diff = 0;
		int hotReference = 0;
		int warmReference = 0;
		int easyHot = 1;
		int easyWarm = 3;
		int mediumHot = 5;
		int mediumWarm = 10;
		int hardHot = 10;
		int hardWarm = 25;
	
		//Welcome message
		System.out.println("Welcome to Nika's number guessing game!");

		do 
		{//9
			//F4
			//Difficulty level 
			System.out.println("Select your difficulty level");
			System.out.println("1. Easy: you must guess a number between 1-10 inclusive.");
			System.out.println("2. Medium: you must guess a number between 1-50 inclusive.");
			System.out.println("3. Hard: you must guess a number between 1-100 inclusive.");
			System.out.println("Please enter the number of the difficulty level you'd like: ");
			int difficulty = input.nextInt();
			
			while(difficulty != 1 && difficulty != 2 && difficulty != 3)
			{
				System.out.println("Sorry, that is not a valid choice.");
				System.out.println("Enter the number of difficulty level you'd like: ");
				difficulty = input.nextInt();
			}
			
			if (difficulty ==  1)
			{
				max = 10;
				hotReference = easyHot;
				warmReference = easyWarm;
			}
			else if (difficulty == 2)
			{
				max = 50;
				hotReference = mediumHot;
				warmReference = mediumWarm;
			}
			else 
			{
				max = 100;
				hotReference = hardHot;
				warmReference = hardWarm;
			}
			
			//generate number 
			int number = rng.nextInt(max - min + 1)+min; 
			System.out.println("--- for reference: the chosen number by the RNG is " + number); //for reference
		
			//generate probability of cheat or not (if/else logic later)
			int cheat = rng.nextInt(100)+1;
			System.out.println("--- Cheat RNG number for reference is: " + cheat);
			if (cheat <= 20)
				System.out.println("--- Therefore, for reference: cheat is happening (aka you cannot guess the number on the first try.)");
			else
				System.out.println("--- Therefore, for reference: no cheat is happening (aka you can guess the number on the first try!)");
			
			//FIRST prompting input
			System.out.println("Guess a number between 1-" + max + " inclusive: ");
			
			do 
			{//1
				//reading from keyboard
				//reassign userNum (not declaring a new int though!)
				userNum = input.nextInt();
				
				//F1
				//ERROR TRAPPING ALGORITHM
				while(userNum < 0 || userNum > max) 
				{//1
					System.out.println("Sorry, that number is not within the required range.");
					System.out.println("Please enter a number between 1-10 inclusive.");
					System.out.println("Guess again: ");
					userNum = input.nextInt();
					
					/* try 
					{//2
						number = input.nextInt();
					}//2
					catch (Exception e)
					{//3
						input.next();//removes the word from the input stream 
					}//3*/
				}//1
				
				tries --;
	
				//F5
				//Program responds with hot, warm and cold depending on how far from the number the guess is
				if (number > userNum)
		            diff = number - userNum;
		        else 
		            diff = userNum- number;
				
				if (userNum != number && tries != 0)
				{//1
					if (diff <= hotReference)
					{//2
					System.out.println("HOT! You are within " + hotReference + " of the secret number.");	
					}//2
					else if (diff <= warmReference)
					{//3
					System.out.println("WARM! You are within " + warmReference + " of the secret number.");		
					}//3
					else 
					{//4
					System.out.println("COLD! You are farther than " + warmReference + " from the secret number.");
					
					System.out.println("Guess again: ");
					
					}//4
				}//1
				
				if (userNum == number && tries == 2 && cheat <= 20) //first condition: if they guess the right num on the first try AND cheat is greater than 20 (cheat is happening)
				{//6
					while(userNum == number) //so it doesnt generate the same number and only regenerates for the first try
						number = rng.nextInt(max - min + 1)+min; //generating new number
					System.out.println("--- for reference: the new number generated by the RNG is " + number); //for reference
					System.out.println("You have 2 attempts left to guess the number correctly!");
				}//6
				else if (userNum == number) //second condition: if they guess the right num at any other point
				{//1
					System.out.println("Nice job! You guessed " + number + " which is correct!");
					win ++;
				}//1
				else if (userNum != number && tries > 0) //third option: output for when they guess the wrong number but have attempts left
				{ //3
						if (tries != 1) 
						{//7
						System.out.println("You have " + tries + " attempts left to guess the number correctly!");
						}//7
						else 
						{//8
						System.out.println("You have " + tries + " attempt left to guess the number correctly!");
						}//8
				}//3	
				else //if they did not guess the right number
				{//5		
				//F3
				//SHOW THE CORRECT NUM TO THE USER AFTER 3 WRONG GUESSES
					System.out.println("Your guess " + userNum + " is incorrect, the correct number would have been " + number + ".");
					lose ++;
				}//5

				if (userNum != number && tries !=0)
					System.out.println("Guess again: ");
				
				
			}while(userNum != number && tries > 0); //1
			
			//F6
			//Score board
			totalPlayed ++;
			
			if (totalPlayed == 1)
				System.out.println("You've played " + totalPlayed + " round... here are your stats:");
			else 
				System.out.println("You've played " + totalPlayed + " rounds... here are your stats:");
			
			if (win == 1)
				System.out.println("You won " + win + " time");
			else 
				System.out.println("You won " + win + " times");
			
			if (lose == 1)
				System.out.println("You lost " + lose + " time");
			else 
				System.out.println("You lost " + lose + " times");

			//F2
			//Play again option
			System.out.println("Would you like to play again? (Y/N)");
			playAgain = input.next().equalsIgnoreCase("Y"); //ignores upper/lower case
			//reset tries back to 3 for new round
			tries = 3;
		}while(playAgain); //9
		
		System.out.println("Thanks for playing! Bye!");

	}
		
}
